### ISSUE TITLE
[DONE] You Could uplaod this to the PROXI repo.

### ISSUE THREAD

**Issue by DarkWav** [ImagicalCorp/Proxi#1]
https://github.com/DarkWav/Proxi

**Comment by keithkfng** [comment]
Lol can you work on it here? I'll give you direct access to the repository.

**Comment by flaxues** [comment]
Is this already working? :P

**Comment by DarkWav** [comment]
1. this is still bleeding (not working)
2. yes i can work on it here if you add me to imagicalcorporation

**Comment by jjplaying** [comment]
Are you sure this can work? I think FastTransfer packet has been removed in Minecraft PE 0.13.

**Comment by flaxues** [comment]
@jjplaying This plugins isn't using the fasttransfer packet :)

**Comment by keithkfng** [comment]
I'm pretty sure it is, it uses StrangePacket.

**Comment by jjplaying** [comment]
Yes I've compared them it's the same packet so it won't work

**Comment by remotevase** [comment]
If I'm correct, @ImagicalGamer 'S proxy doesn't use the fast transfer packet

**Comment by remotevase** [comment]
Updated README to support ImagicalMine not PocketMine nor Nukkit

**Comment by jjplaying** [comment]
@remotevase Yes I think proxies work like BungeeCord with no fast transfer packet, but he didn't published it, did he?

**Comment by remotevase** [comment]
I believe not

**Comment by DarkWav** [comment]
a few things about the plugin:
1. This is a modyfied version of fasttransfer and it uses strangepacket wich is not working.
(That´s why I say the project is unfinished.)
2.I not know If I can EVER fix strangepacket because I`m not coding any servers, only plugins.
3. @flaxues sadly, i have to say you´re wrong. this is a fork of fasttransfer wich won´t work with mcpe 0.13.0 or higher.
4.@jjplaying, you´re right, this uses fastransfer packet it is, as I sayed, still bleeding (not working.)
5.The process is finished about 40% This still needs a lot of code.
-Darku

**Comment by DarkWav** [comment]
I think shis should be closed.
